# Generated by Django 5.0.7 on 2024-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comapny', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
